### ISSUE TITLE
Vectorize day_of_week()

### ISSUE THREAD

**Issue by rstub** [rstub/swephR#1]
The current implementation of `day_of_week()` is not very R-like, since it takes only a single argument of type `double` instead of a numeric vector.

**Comment by vreijs** [comment]
I included the vector concept by adding a wrapper to all my (single value) VBA functions)...
Did that in the following way (this is an example, but the principle is used for any amount of arguments):
###################################################################
AppAltfromDip <- function (HObs,
                           HeightDist,
                           TObs = TempDefault,
                           PObs = PressureDefault,
                           Lapse = LapseDefault,
                           Lat = AverageLat) {
  functionvector <-
    data.frame(HObs, HeightDist, TObs, PObs, Lapse, Lat)
  #  print(functionvector)
  ResultVector <- c(0)
  for (i in 1:nrow(functionvector))
  {
    ResultVector[i] = S_AppAltfromDip(
      functionvector$HObs[i],
      functionvector$HeightDist[i],
      functionvector$TObs[i],
      functionvector$PObs[i],
      functionvector$Lapse[i],
      functionvector$Lat[i]
    )
  }
  return(ResultVector)
}

I am sure this could be make more generalised!

All the best,


Victor
