### ISSUE TITLE
Methods needed by ARCHAEOCOSMO

### ISSUE THREAD

**Issue by rstub** [rstub/swephR#12]
[ARCHAEOCOSMO](https://github.com/vreijs/ARCHAEOCOSMO) will be the first "client" package to use swephR. Here the required methods:

- [x] swe_azalt
- [x] swe_calc
- [x] swe_day_of_week
- [x] swe_deltat
- [x] swe_deltat_ex
- [x] swe_fixstar2
- [x] swe_fixstar2_mag
- [x] swe_get_tid_acc
- [x] swe_heliacal_angle
- [x] swe_heliacal_pheno_ut
- [x] swe_heliacal_ut
- [x] swe_lun_eclipse_how
- [x] swe_lun_eclipse_when
- [x] swe_pheno_ut
- [x] swe_rise_trans
- [x] swe_rise_trans_true_hor
- [x] swe_set_delta_t_userdef
- [x] swe_set_ephe_path
- [x] swe_set_topo
- [x] swe_sol_eclipse_when_loc
- [x] swe_topo_arcus_visionis
- [x] swe_version
- [x] swe_vis_limit_mag

Available but not used functions:

- swe_difdegn
- swe_pheno
- swe_set_jpl_file
- swe_sol_eclipse_how
- swe_sol_eclipse_when_glob

**Comment by vreijs** [comment]
Hello Ralf,
A few functions are not used in ARCHAEOCOSMO (I know hey are defined, but nowhere used), so they are not part of the list. I will work on the remaining ones soon.
'not used in ARCHAEOCOSMO
Public Declare Sub swe_set_jpl_file Lib "C:\ARCHAEOCOSMO\AddIns\swedll32.dll" _
        Alias "_swe_set_jpl_file@4" ( _
          ByVal file As String _
        )

'not used in ARCHAEOCOSMO
Private Declare Function swe_difdegn Lib "C:\ARCHAEOCOSMO\AddIns\swedll32.dll" _
        Alias "_swe_difdegn@16" ( _
          ByVal P1 As Double, _
          ByVal P2 As Double _
        ) As Long
                    
'not used in ARCHAEOCOSMO
Private Declare Function swe_sol_eclipse_how Lib "C:\ARCHAEOCOSMO\AddIns\swedll32.dll" _
        Alias "_swe_sol_eclipse_how@24" ( _
          ByVal tjd_ut As Double, _
          ByVal ifl As Long, _
          ByRef geopos As Double, _
          ByRef attr As Double, _
          ByVal serr As String _
        ) As Long
                        ' serr must be able to hold 256 bytes
                        ' geopos must be first of three array elements
                        ' attr must be first of twenty array elements

'not used in ARCHAEOCOSMO
Private Declare Function swe_sol_eclipse_when_glob Lib "C:\ARCHAEOCOSMO\AddIns\swedll32.dll" _
        Alias "_swe_sol_eclipse_when_glob@28" ( _
          ByVal tjd_start As Double, _
          ByVal ifl As Long, _
          ByRef ifltype As Long, _
          ByRef tret As Double, _
          ByVal backward As Long, _
          ByVal serr As String _
        ) As Long
                        ' serr must be able to hold 256 bytes
                        ' tret must be first of ten array elements

'not used in ARCHAEOCOSMO
Private Declare Function swe_pheno Lib "C:\ARCHAEOCOSMO\AddIns\swedll32.dll" _
        Alias "_swe_pheno@24" ( _
          ByVal tjd As Double, _
          ByVal ipl As Long, _
          ByVal iflag As Long, _
          ByRef attr As Double, _
          ByVal serr As String _
        ) As Long      ' serr must be able to hold 256 bytes

**Comment by vreijs** [comment]
Have now also implemented: swe_sol_eclipse_how and swe_rise_trans

**Comment by rstub** [comment]
Ok. I have moved the not used functions to a separate list and ticked off the functions you implemented in #15.

**Comment by rstub** [comment]
Several functions where added in #17. According to the list `swe_heliacal_angle()` is the last missing function. Correct?

**Comment by vreijs** [comment]
That is indeed correct, but it is an undocumented function of SE;-) And I
only use it for specific tests. The swe_topo_arcus_visionis is also
undocumented, but that one is handy for certain testing (and checking if
swe_heliacal_ut is working correct in 'corner' cases). I need to check if I
still use this swe_heliacal_angle in one of my research (it is used within
swe_heliacal_ut, but that is internal)... So leave it with me if that one
needs to be added (but I think not).

**Comment by rstub** [comment]
Now that `swe_helical_angle` is also merged we can close this issue.
