### ISSUE TITLE
results from swe_fixstar(2)(-mag)

### ISSUE THREAD

**Issue by vreijs** [rstub/swephR#14]
I have some unexpected results from swe_fixstar(2):
It looks swe_fixstar works ok:
> swe_set_ephe_path("")
> swe_set_topo(0,50,10)
> swe_fixstar("sirius",1234567,34818)
$`return`
[1] 34818
$star
[1] "Sirius,alCMa"
$xx
[1]  6.465315e+01 -1.780315e+01  5.518192e+05 -3.482530e-04  1.170200e-05 -3.109594e-03
$serr
[1] "SwissEph file 'seplm18.se1' not found in PATH '\\sweph\\ephe\\' \nusing Moshier eph.; "

swe_fistar2 should give same results, but does not provide the correct xx and starname data:
> swe_fixstar2("sirius",1234567,34818)
$`return`
[1] -1
$star
[1] "Sirius,alCMa"
$xx
[1] 0 0 0 0 0 0
$serr
[1] "SwissEph file 'seplm18.se1' not found in PATH '\\sweph\\ephe\\'"

Then looking at swe_fixstar_mag seems to be going wrong when called more than once with the same starname:
> swe_fixstar_mag("sirius")
$`return`
[1] 0
$star
[1] "Sirius,alCMa"
$mag
[1] -1.46
$serr
[1] ""
> swe_fixstar_mag("sirius")
$`return`
[1] 0
$star
[1] "sirius"
$mag
[1] 1.302323e-262
$serr
[1] ""

swe_fixstar2_mag though works ok:
> swe_fixstar2_mag("sirius")
$`return`
[1] 0
$star
[1] "Sirius,alCMa"
$mag
[1] -1.46
$serr
[1] ""
> swe_fixstar2_mag("sirius")
$`return`
[1] 0
$star
[1] "Sirius,alCMa"
$mag
[1] -1.46
$serr
[1] ""
> 

What do other people see? (the authors of SE don't see this behavior, but they are of course only using complied C).

Thanks for the feedback.

**Comment by rstub** [comment]
I used copy'n'paste to create a `swe_fixstar2` out of `swe_fixstar`. In my (not very systematic) testing I had the impression that `swe_fixstar` would fall back to Moshier, even when called with the flag for SE. `swe_fixstar2` does not do that. After increasing the flag value to `34820`, also `swe_fixstar2` worked for me.

**Comment by vreijs** [comment]
On 20 August 2018 at 05:55, Ralf Stubner <notifications@github.com> wrote:

> swe_fixstar2 does not do that. After increasing the flag value to 34820,
> also swe_fixstar2 worked for me.
>
I get different results:

> swe_fixstar("sirius",1234567,34820)$`return`
[1] 34820
$star
[1] "Sirius,alCMa"
$xx
[1]  6.465734e+01 -1.780520e+01  5.518188e+05  6.505714e-04
-5.711603e-04  7.407493e-03
$serr
[1] ""
> swe_fixstar2("sirius",1234567,34820)$`return`
[1] 34820
$star
[1] "Sirius,alCMa"
$xx
[1]     64.65734    -17.80520 551818.75344      0.00000      0.00000
   0.00000
$serr
[1] ""


>
The last three entries [speeds] with swe_fixstar2 are zero... It looks
swe_fixstar2 is behaving differently around the ephemeris, I had queried
this on the swiss ephemeris e-group, but no answer yet from the authors.
Hope soon to know what is the real cause (VBA behaves similar as R).

Thanks for testing! swe_fixstar(2)_mag also behave strange (both in R and
VBA). Hope to hear also about that.

**Comment by rstub** [comment]
Problem solved and only  `swe_fixstar2(_mag)` merged in #15.
