### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by vreijs** [rstub/swephR#18]
I get several compiling errors in the sweph C code. Do we need to solve these before we put it on CRAN? So do we need to start working on this on the swisseph e-group?
I can provide an updated version (I think I got the last few days a new error;-) Let me know.

**Comment by vreijs** [comment]
Here are the places I get compiling warnings (there are experienced during different times doing 'Load All' or 'Clean and Rebuild':
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/VRHome/Documents/R/win-library/3.5/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c libswe/swepcalc.c -o libswe/swepcalc.o
libswe/swepcalc.c: In function 'nacalc':
libswe/swepcalc.c:121:41: warning: 'rspeed' may be used uninitialized in this function [-Wmaybe-uninitialized]
       if (pspe != NULL) pspe [planet] = swe_d2l (rspeed * DEG);
                                         ^
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/VRHome/Documents/R/win-library/3.5/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c libswe/sweph.c -o libswe/sweph.o
libswe/sweph.c: In function 'swecalc':
libswe/sweph.c:4046:5: warning: 't' may be used uninitialized in this function [-Wmaybe-uninitialized]
     swi_bias(xx, t, iflag, FALSE);
     ^
libswe/sweph.c:3913:10: note: 't' was declared here
   double t; 
          ^
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/VRHome/Documents/R/win-library/3.5/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -UNDEBUG -Wall -pedantic -g -Og -c libswe/swehouse.c -o libswe/swehouse.o
libswe/swehouse.c: In function 'sunshine_solution_makransky':
libswe/swehouse.c:2589:7: warning: 'r' may be used uninitialized in this function [-Wmaybe-uninitialized]
    cu = 180 + r;
       ^
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I./libswe/ -I"C:/Users/VRHome/Documents/R/win-library/3.5/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -UNDEBUG -Wall -pedantic -g -Og -c libswe/swejpl.c -o libswe/swejpl.o
libswe/swejpl.c: In function 'fsizer':
libswe/swejpl.c:194:10: warning: variable 'nrd' set but not used [-Wunused-but-set-variable]
   size_t nrd; /* unused, removes compile warnings */
          ^
libswe/swejpl.c: In function 'state':
libswe/swejpl.c:653:10: warning: variable 'nrd' set but not used [-Wunused-but-set-variable]
   size_t nrd; /* unused, removes compile warnings */
          ^

C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I./libswe/ -I"C:/Users/VRHome/Documents/R/win-library/3.5/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -UNDEBUG -Wall -pedantic -g -Og -c libswe/sweph.c -o libswe/sweph.o
libswe/sweph.c: In function 'app_pos_etc_moon':
libswe/sweph.c:4038:5: warning: 't' may be used uninitialized in this function [-Wmaybe-uninitialized]
     swi_bias(xx, t, iflag, FALSE);
     ^

**Comment by vreijs** [comment]
On the Debian warning,I got the below response from the SE authors (so hopefully the next release they will updated that). So that is hopefully good progress on this warning.

====
This will be fixed in the next release.

Please report source code context when you report error messages with line numbers, the best is a few numbers code lines like

    Show message history

Victor, for the moment cut off fstdata.starbayer before the sprintf() statement:

fstdata.starbayer[38] = '\0';
Then it will have at most 38 characters, and will fit with the prefixed comman into fstdata.skey which is defined as holding 40 bytes, i.e. 39 characters and a null terminator.


Dieter, I propose to change sweph.h to
   
#define SWI_STAR_LENGTH 40
struct fixed_star {
  char skey[SWI_STAR_LENGTH + 2]; // may be prefixed with comma, one char more
  char starname[SWI_STAR_LENGTH + 1];
  char starbayer[SWI_STAR_LENGTH + 1];
  char starno[10];
  double epoch, ra, de, ramot, demot, radvel, parall, mag;
};   

and in the code, for variables like last_starbayer, write char[SWI_STAR_LENGTH + 1] instead of char[40].

Then we have 40 char for actual name, plus one for the null terminator.

In skey, we have one more because it takes starnames prefixed with a comma.
If a compiler is really clever enough to check the definition of the array size,
the effects of the printf pattern and the potential size of the string copied in,
and complain when it might be overwritten, it will then be silent.

Of course it has to be verified where star names come in from files or user input, that strlen(name) <= SWI_STAR_LENGTH,
and cut off if they are longer.

**Comment by rstub** [comment]
Unfortunately the intelligence of compilers is so limited, it does not recognize the safe-guard introduced by `fstdata.starbayer[38] = '\0';`.  However, a simple patch like this quiets the compiler:

```
diff --git a/src/libswe/sweph.h b/src/libswe/sweph.h
index 05d2222..c1f40e5 100644
--- a/src/libswe/sweph.h
+++ b/src/libswe/sweph.h
@@ -586,7 +586,7 @@ struct sid_data {
 };
 
 struct fixed_star {
-  char skey[40];
+  char skey[41];
   char starname[40];
   char starbayer[40];
   char starno[10];
```

Since this is almost the same as suggested as the real solution, I would use that for now.

**Comment by rstub** [comment]
BTW, here some compiler warnings from clang on MacOS that where serious enough to produce a WARNING from `R CMD check`:

Found the following significant warnings:
```
libswe/sweph.c:278:12: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
libswe/swehel.c:231:13: warning: explicitly assigning value of variable of type 'double' to itself [-Wself-assign]
libswe/swehel.c:556:11: warning: explicitly assigning value of variable of type 'int32' (aka 'int') to itself [-Wself-assign]
libswe/swehel.c:1268:9: warning: explicitly assigning value of variable of type 'double' to itself [-Wself-assign]
libswe/swehel.c:3253:9: warning: comparison of array 'serr' not equal to a null pointer is always true [-Wtautological-pointer-compare]
``` 

I have already included patches for these issues in `external/path` in particular:

* `02_correct_error_string.diff`
* `03_fix_self_assign.diff`
* `06_tautological_compare.diff`

Can you send these warnings together with my proposed patches to the list? You might also include `04_constant_logical_operand.diff`, which I found via a less critical warning, but which I think fixes a real bug. The other two patches require a bit more thought on my side.

**Comment by vreijs** [comment]
I forwarded this message to the swissephe e-group (and uploaded all diff
files to that e-group also).

**Comment by vreijs** [comment]
Some feedback from Dieter (one of the main SE authors):
"Hello Victor,

thanks a lot for all the clues and patches. I did not react much becaus I was ill (and still am), but they will all be included in the next release.

Best,

Dieter"

So I think it will be covered (I have told him that we will always be willing to help/explain/etc.

**Comment by vreijs** [comment]
I think we will need to wait for the next version, to see if SE authors made the needed changes have been done. So for me this one is closed.
