### ISSUE TITLE
swe_heliacal_ut

### ISSUE THREAD

**Issue by vreijs** [rstub/swephR#19]
I 'activated' swe_heliacal_ut in testheliacal.R (and in test-misc.R), but it causes instability of RStudio (makes it restart). RStudio restarts after running several times (can't yet reproduce it how many times, soemtiem sit looks one even) the swe_heliacal_ut function . So all looks ok (and the correct results are printed) and then after a few seconds RStudio restarts. If I use my ARCHAEOCOSMO functions (which uses swe_heliacal_ut): no restart happens. Don't yet know how to debug....
The dret results of swe_heliacal_ut has these very large/small numbers, perhaps that does some damage?

**Comment by rstub** [comment]
The issue with the restarts should be fixed now. Problem was a too short input vector.

The issue with the additional very large/small numbers seems to be the following: We allocate memory for the output values, but we do not initialize it. Currently SE uses only the first few array elements. The others are not touched and stay in their uninitialized form. Two solutions:

* Return only those values that actually make sense like this:

           Rcpp::Named("dret") = Rcpp::NumericVector::import(dret.begin(), dret.begin() + 3)

    This requires hard-coding these numbers in C++. But we can remove the return sub-setting in the test code. 

* Initialize the memory to 0. That makes sense anyway.

**Comment by vreijs** [comment]
On 9 September 2018 at 09:33, Ralf Stubner <notifications@github.com> wrote:

>
>    -
>
>    Initialize the memory to 0. That makes sense anyway.
>
>
I would initialise it, as that would need to least change control when
things are change din SE. Hopefully the the array-length are large enough
(as these were deifne dby SE people).

**Comment by rstub** [comment]
I was doing that already, c.f. commit https://github.com/rstub/swephR/pull/17/commits/c3785090df3e13dd2ffd6e5372db83c5950dd882
