### ISSUE TITLE
use mustWork = TRUE

### ISSUE THREAD

**Issue by rstub** [rstub/swephR#24]
https://github.com/rstub/swephR/blob/910443cf7a7e299ca7120370a5c30e607d1f6ba4/R/zzz.R#L3

**Comment by vreijs** [comment]
I still need to check if this idea works. I assume I need to install first myseflf swephRdata, correct?
I did that in the past, but I think I still get the error message with swe_calc that it does not find SWIEPH, but I will some time and try to debug and understand.
Before we put things on CRAN, we need to decide on the name of the SWIEPH data...

**Comment by rstub** [comment]
This issue is more of a reminder that the current code is a bit to optimistic. With the default `mustWork = FALSE`, `system.file` returns an empty string if the directory does not exist. That's not what I want here. If `swephR` or the data package is installed, it is an error if the `ephemeris` sub-directory does not exist.
