### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rstub** [rstub/swephR#26]
The documentation needs some improvements. For the help pages:

- [x] Links to the general and programmer manual

- [x] More logical order of functions

- [ ] some simple examples

- [ ] descriptions what each function does and what it returns

A vignette would also be nice. A simple idea would be to port and explain the example programs from the programmers guide.

**Comment by vreijs** [comment]
I will put some time into this. I know I have been a little inactive on this front, but I would like to do something. The ?swe_xxx need sot be filled in, but how does that work because the @param are now put together? I also would like to have in the ?swe_xxx the values of the flags (and not the flag names (of the flag names are handy, but the value is more direct and these flags are also not explicit available in R...).
Are the examples different then the tests? It would be great to have them similar, but can these be 'integrated'?

**Comment by vreijs** [comment]
Another reason why I want to work on the descriptions is also to finalise the feedback on the sweph manual (swephprg.docx)  of the SE authors (I have several remarks/errors/typos which I want to communicate with the SE authors).

**Comment by rstub** [comment]
Can you name one or two functions or arguments that you would like to work on? Than I could point you to the place where the documentation should go.

**Comment by vreijs** [comment]
Let me do swe_calc and swe_topo_arcus_visionis (they have extensive input
parameters and some output parameters that need to be defined)

**Comment by rstub** [comment]
> (and not the flag names (of the flag names are handy, but the value is more direct and these flags are also not explicit available in R...).

Actually, that is something I want to change, c.f. this commit in another branch https://github.com/rstub/swephR/commit/091f4e3a0f4b110b2172657762750ea56a869fdb
I think it would be useful to have the bodies and flags as lists available. One could than use

```
swe_calc(2458346.82639, bodies$SUN, flags$MOSEPH)
```

which I think is clearer than the current 

```
swe_calc(2458346.82639, 0, 4)
```

Concerning the `@params`: I hope that for all equally named parameters, one description per help page is sufficient. If this is not true, then we should split up the help pages. In addition, there are some parameters that seem to mean the same thing (e.g. `tjd_start` and `tjdstart`). We could either rename those in documentation and code to a common name. Or, if we want to follow SE closely, combine the documentation:

```
//' @param tjd_start,tjdstart  ...description...
```

Concerning the two functions: For `swe_calc`, documentation should go into `R/calculation.R`. I have added some generic placeholders in there (`@description`, `@details` and `@return`) that you can expand upon. For `swe_topo_arcus_visionis` the right file would be `src/eclipse_pheno.cpp`.

**Comment by rstub** [comment]
Concerning examples:
This would be example code that is listed on the help pages. We could use code from the unit tests for this.

**Comment by vreijs** [comment]
On 22 September 2018 at 22:05, Ralf Stubner <notifications@github.com>
wrote:

> (and not the flag names (of the flag names are handy, but the value is
> more direct and these flags are also not explicit available in R...).
>
> Actually, that is something I want to change, c.f. this commit in another
> branch 091f4e3
> <https://github.com/rstub/swephR/commit/091f4e3a0f4b110b2172657762750ea56a869fdb>
> I think it would be useful to have the bodies and flags as lists
> available. One could than use
>
> swe_calc(2458346.82639, bodies$SUN, flags$MOSEPH)
>
>
Is indeed a nice way of doing it. Could we use the same names as in SE?
That would save us defining things. I know these are sometimes longer, but
not always: bodies*SUN ->  SE_SUN or flags$MOSEPH -> SEFLG_MOSEPH.

> Concerning the @params: I hope that for all equally named parameters, one
> description per help page is sufficient. If this is not true, then we
> should split up the help pages. In addition, there are some parameters that
> seem to mean the same thing (e.g. tjd_start and tjdstart). We could
> either rename those in documentation and code to a common name. Or, if we
> want to follow SE closely, combine the documentation:
>
> //' @param tjd_start,tjdstart  ...description...
>
> I am now using one name instead of multiple ones. so iflag, ifl and
ephe_flag are the same and I called them ephe_flag. tjdxxx I made jd, jf_ut
or jd_et. and jdstart.

> Concerning the two functions: For swe_calc, documentation should go into
> R/calculation.R. I have added some generic placeholders in there (
> @description, @details and @return) that you can expand upon. For
> swe_topo_arcus_visionis the right file would be src/eclipse_pheno.cpp.
>
I now worked on misc, eclipse_pheno and calculation. For some reason I
can't add an //' @title to the calcluation.cpp. Please have a look if it is
now more consistant.

**Comment by vreijs** [comment]
On 22 September 2018 at 22:13, Ralf Stubner <notifications@github.com>
wrote:

> Concerning examples:
> This would be example code that is listed on the help pages. We could use
> code from the unit tests for this.
>
I think we should indeed use the same test for the help file as in the
testhat.

**Comment by vreijs** [comment]
I think we need to use for each section in the swephprf.docx another cpp. and even mention the section in the name. IN that way the documentation of SE itself matches easier to the swephR. What do you think?

**Comment by vreijs** [comment]
That works indeed. I understand the changes (also like the @details command). You had the wish list, do the example need more explanation (or I am confusing it with the testthat). A better description of the functions would indeed be good. I will have a go and try to cut and paste form the swephprg.doc page.

**Comment by vreijs** [comment]
\i

**Comment by rstub** [comment]
@vreijs Why did you close this issue?
