### ISSUE TITLE
CRAN pre-test WARNING

### ISSUE THREAD

**Issue by rstub** [rstub/swephR#37]
> Flavor: r-devel-linux-x86_64-debian-gcc
> Check: whether package can be installed, Result: WARNING
>   Found the following significant warnings:
>     libswe/sweph.c:7363:5: warning: 'strncpy' output may be truncated copying 256 bytes from a string of length 275 [-Wstringop-truncation]
>   See '/srv/hornik/tmp/CRAN/swephR.Rcheck/00install.out' for details.

**Comment by vreijs** [comment]
Also don;t understand the warning. I would say that truncating to 256 is what is wanted (as that is the function of strncpy)... Sorry I have no idea.

**Comment by rstub** [comment]
Right. This looks like intended behavior. Do you know where the format for `sefstarts.txt` is documented? In particular w.r.t. allowed length of names? So far I have only found:

> The function and the DLL should survive damaged sefstars.txt files which contain illegal data and star names exceeding the accepted length. Such fields are cut to acceptable length.

https://www.astro.com/swisseph/swephprg.htm#_Toc505244844
