### ISSUE TITLE
char* as input argument of version()

### ISSUE THREAD

**Issue by vreijs** [rstub/swephR#4]
Thanks for this version code!
I see that you iitialise the 'version' string inside the C code: 
char *version = (char*) malloc(256*sizeof(char));

But would it be possible to provide the initialisation in R function call (such as the serr string in swe_calc)? SE uses that method quiet a lot (just to keep semantics similar). I tried to remove the char *version statement and put part in the std::string version(char *version), but is not liked by Rcpp...
Perhaps I am really lacking C skill...

All the best,

Victor

**Comment by rstub** [comment]
From my reading of the documentation I gather that SE expects a string variable of specific size at this point. I don't see how we could assure that when memory is allocated in R. I am not sure why this would be necessary, though. For swe_calc, the return code indicates if an error has occurred. I suggest we do (pseudo code)

    if(rc == ERROR)
      Rcpp::stop(serr);

BTW, I have changed the memory allocation at that point to a more C++ way:

    std::array<char, 256> version;

**Comment by vreijs** [comment]
SE expects the calling program to reserve the space (with proper size) for any string , and then the function (in R) writes into that space (by using the pointer). I also don't know why SE has chosen for that, but it looks to be quite generically used. In most functions that are not entered into the swephR.cpp  this is happening. Like serr, Star, ObjectName, 
[SE-ARCHAEOCOSMO.txt](https://github.com/rstub/swephR/files/2279728/SE-ARCHAEOCOSMO.txt)
