### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by rstub** [rstub/swephR#47]
In the documentation we have lot's of links like http://www.astro.com/swisseph/swephprg.htm?lang=g#_Toc505244831, which used to go to specific sections in the manual. With the new upstream release, these links are broken. I don't think it makes sense to update these links for every release, so it is probably best to only refer to

> Section xy in http://www.astro.com/swisseph/swephprg.htm

**Comment by vreijs** [comment]
Agree.

**Comment by rstub** [comment]
fixed by #46
