### ISSUE TITLE
Understand and find ASAN errors

### ISSUE THREAD

**Issue by rstub** [rstub/swephR#52]
Release v0.2.0 was bitten by ASSAN errors found only CRAN, even though `rhub::check_with_sanitizers()` was used:

- [ ] Try to understand why this error was not found
- [x] Implement a testing scheme to find such problems reliably

Maybe interesting: https://github.com/rocker-org/r-devel-san/issues/3 and https://github.com/jeroenooms/curl/blob/master/docker/r-devel-san/Dockerfile

**Comment by rstub** [comment]
Hopefully this can be fixed via rhub, c.f. https://github.com/r-hub/rhub/issues/290

**Comment by rstub** [comment]
Steps to reproduce issue with version 0.2.0 and check current version:

```
$ docker run --rm -it --net host -v $(pwd):/swephR rocker/r-devel-ubsan-clang bash
# export ASAN_OPTIONS='detect_leaks=0:detect_odr_violation=0'
# RD -e "install.packages('swephR', dependencies = TRUE)"
# RD CMD build /swephR/
# export _R_CHECK_FORCE_SUGGESTS_=false
# RD CMD check swephR_0.2.1.1.tar.gz 
# wget https://cran.r-project.org/src/contrib/Archive/swephR/swephR_0.2.0.tar.gz
# RD CMD check swephR_0.2.0.tar.gz 
```

**Comment by rstub** [comment]
Probably useful: https://github.com/wch/r-debug

**Comment by rstub** [comment]
The [docker image](https://hub.docker.com/r/rstub/swephr-debug) is now automatically build upon each push to `master` I am not sure yet if/how PRs are handled. This docker image checks the `swephR` package using current R-devel with valgrind, gcc UBSAN and clang UBSAN.

With this image v0.2.0 would have thrown an error, while current version is fine.

@vreijs We can go for the next release once CRAN opens up again on Aug 18. Should we go for version number 0.3.0 given that the full C API is now covered?

**Comment by vreijs** [comment]
A pity it is not understood why it is solved. But hopefully the reason is academic (If it does not occur anymore...)
Lets go for 0.3.0: indeed we now have the full API, so worth doing that. Thanks for all your work.
