### ISSUE TITLE
Julian Day to UTC

### ISSUE THREAD

**Issue by ockober** [rstub/swephR#55]
Thank you very much for your work to port SwissEph into R. 
I'm trying to replicate Delta T by using _swe_deltat_ex(jd_ut, ephe_flag)_. However, the function _swe_jdet_to_utc_  to transform ET to UT to derive _jd_ut_ is not available in Section 7: Date and time conversion functions.  In principle I would like to replicate the output from swewin32.exe, which comes along with the source code to verify my R code. Do you plan to add the functions from 7.2 as well?

**Comment by rstub** [comment]
This function is supported in the latest development version (c.f. https://github.com/rstub/swephR/commit/8bddb7cb42fe8e99dbd7b0b02ac35980c5bbac30), which supports the full C API of libswe. If you have the necessary development tools available you can install it via `remotes::install_github("rstub/swephR")`.

**Comment by ockober** [comment]
Thank you very much.
