### ISSUE TITLE
New WARN on CRAN

### ISSUE THREAD

**Issue by rstub** [rstub/swephR#62]
CRAN has started to turn on the compiler option `-Wstrict-prototypes` on some platforms leading to new WARN:

> Version: 0.3.0
> Check: whether package can be installed
> Result: WARN
>     Found the following significant warnings:
>      ./libswe/swephlib.h:120:33: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      ./libswe/swephlib.h:130:34: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/swejpl.c:949:24: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/swemmoon.c:1183:18: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/swemmoon.c:1368:18: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/swemmoon.c:1445:18: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/swemmoon.c:1459:18: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/swemmoon.c:1764:26: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/swemmoon.c:1821:22: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      ./libswe/swepcalc.h:120:33: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/swepcalc.c:373:26: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/swephlib.c:3001:33: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/swephlib.c:3033:26: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
>      libswe/sweph.c:7099:27: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
> Flavor: [r-devel-linux-x86_64-fedora-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/swephR-00check.html)
> 
> Version: 0.3.0
> Check: whether package can be installed
> Result: WARN
>     Found the following significant warnings:
>      libswe/swephlib.h:120:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
>      libswe/swephlib.h:130:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
>      libswe/swepcalc.h:120:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
>      libswe/swepcalc.c:373:7: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
>      libswe/sweph.c:7099:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
>      libswe/swephlib.c:3033:7: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
> Flavor: [r-devel-linux-x86_64-fedora-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/swephR-00check.html)

- [ ] Reproduce locally
- [ ] Build a patch for SE
- [ ] communicate the patch upstream

**Comment by vreijs** [comment]
Shall I inform the Swiss Ephemeris people about these?

**Comment by rstub** [comment]
You mean they might might build the patch? That would be interesting. They would have to compile using `-Wstrict-prototypes`, preferably using clang15, to get these warnings relative to their code base. In our code base line numbers might be different.

**Comment by vreijs** [comment]
I now understand  this -Wstrict -prototypes is not important for the code itself (only for compiling). In that case I do not think we need to  communicate this with the swiss ephemeris people.

**Comment by rstub** [comment]
There will be code changes necessary in order to remove these warnings, similar to what we had before. So at some point it would make sense to communicate that upstream.

**Comment by vreijs** [comment]
Ok I will inform them that it is now important to use the  -Wstrict -prototypes options when compiling (and resolve the resulting errors). If this statement is not correct, please let me know what I need to tell them. Thanks.

All the best,

Victor

**Comment by vreijs** [comment]
Hello Ralf,

Are these warnings which happened in October still present in 2.10.03?

All the best,

Victor

**Comment by rstub** [comment]
So far I am not seeing them. But I have not tested yet with an explicit `-Wstrict-prototypes` option.

**Comment by rstub** [comment]
Good news, Victor!
By using `gcc-12` with explicit `-Wstrict-prototypes` I was able to reproduce these warnings with the currently released version of swephR, but not with version 2.10.03. We can go for a new release once we know to what extend tests should be adjusted.

**Comment by rstub** [comment]
fixed by #60

**Comment by rstub** [comment]
I got a message from CRAN that I need to fix the currently existing WARN messages until 5.5. While retesting the current version I found that #60 did not fix things completely.
