### ISSUE TITLE
fixstar ... 

### ISSUE THREAD

**Issue by vreijs** [rstub/swephR#7]
Amazing what different principles can be use din function calls;-) But I think I got it to work: 
> swe_set_topo(0,50,10)
> swe_set_ephe_path("c:\\ARCHAEOCOSMO\\ephe")
> swe_fixstar("sirius",123456,34818)
$`return`
[1] 34818
$star
[1] "Sirius,alCMa"
$xx
[1]  3.175829e+01 -2.804553e+01  5.592892e+05  8.725749e-04 -3.930304e-04  7.815862e-03
$serr
[1] "SwissEph file 'seplm48.se1' not found in PATH 'c:\\ARCHAEOCOSMO\\ephe\\'"
> 
It works. But perhaps it can be optimised. Let me know.

**Comment by vreijs** [comment]
By the way, there are always quotes around the first name in the list (like 'return', but I see the quotes with any name). I don't see these quotes in the other members of the list...

**Comment by vreijs** [comment]
Made now also azalt function. With results:
> swe_azalt(1234567,1,c(0,50,10),1013.25,15,c(293.289912187766,-22.1022285626333)) 
$`xaz` [1] 356.79484  17.83857  17.88800

These results are the same as I am using VBA ARCHAEOCOSMO. 
For some reason I am not able to see the swephR functions in my ARCHOAECOSMO (it seems my additions are for some reason not picked up in the ARCHAEOCOSMO session, perhaps I need to 'export' my new swephR functions (I see the ones gotten form your master)... Or do I need to do a pull from local??? Another instant of my beginners knowledge...

**Comment by vreijs** [comment]
I had some errors in the \code statements. But I am still not able to see the newly made functions (fixstars and azalt) in my own package. 
[fixstars-azalt-R-02.zip](https://github.com/rstub/swephR/files/2284980/fixstars-azalt-R-02.zip)

**Comment by rstub** [comment]
A few comments:

* Please use `star.resize(41);` to ensure that `star` has space for at least 41 characters.
* Please try to commit and push these changes in your fork. This would make integration for me easier.
* In order to see the new functions in our package, you have to install `swephR` locally. It is also a good idea to restart the `ARCHOAECOSMO` session, so that the new `swephR` version can be loaded.

**Comment by vreijs** [comment]
Thanks Ralf,

On 14 August 2018 at 08:44, Ralf Stubner <notifications@github.com> wrote:

> A few comments:
>
>    - Please use star.resize(41); to ensure that star has space for at
>    least 41 characters.
>
> This looks better than adding 41 spaces (as I did now, so I was sure it
was always bigger than 41 char)

>
>    - Please try to commit and push these changes in your fork. This would
>    make integration for me easier.
>
>
I will now start to work on understanding how to do this forking. I
understand that that would be easier for both of us. I will do this this
afternoon.


>
>    - In order to see the new functions in our package, you have to
>    install swephR locally. It is also a good idea to restart the
>    ARCHOAECOSMO session, so that the new swephR version can be loaded.
>
>
I did a lot of things (stopped RStudio, have two sessions [swephR and
ARCHAEOCOSMO] in RStudio, do multiple rebuilds, roxyginese, start stop
laptop, etc. etc. etc. ) and then see if ARCHAEOCOSMO can see it. But I was
not lucky.
How do I 'install swephR locally'? And I should install the fork (say
swephR-1, and then also refer to swephr-1:::).
The interesting thing: when I typed (on command window) 'swephr::' I only
saw in dropdown menu only the 'old' list of functions, if I did three
'swephR:::') then I saw also my new function, but when run the new
function, it was not found.

Sorry for this beginners questions.

All the best,


Victor

**Comment by vreijs** [comment]
I realised that you mean(I assume) 'Install and Restart' in RStudio. I think I also tried that yesterday also, but will try again later today.

**Comment by rstub** [comment]
If the functions can be called as swephR:::..., than the package is
installed.  However, roxygen2 has not added them to NAMESPACE. Calling
devtools::document() should fix that.

**Comment by vreijs** [comment]
Will try that: had not done that yet... I experienced that doing multiple
roxyginese after each other miraculous sometiems solve the problem.
I at this moment seem to have all type of problems: warnings when building
that I am out of memory as I use more than use 2.9 GByte; that setting a
breakpoint gives me an error that program is out of indexes, hanging edit
window in RSutio, values that become NULL while they are not NULL, etc.

So it looks something is wrong (in VBA is was due to pointers [of strings]
that were wrong;-). Perhaps the R environment is also not save for that.
Will see if I can get a more stable response (when a beginner sees these
problems, they don't help to get/learn a good workflow;-).

All the best,


Victor

**Comment by vreijs** [comment]
I made again a fork of your swephR and it is at:  https://github.com/vreijs/swephR
And I pushed my changes (I don't understand why I had to Pull first from this repository before I coudl Push, even while I know nobody changed anything!). 
I have this behavior also with my ARCHOEACOSMO package (nobody looks at it [yet]) and still I sometimes need to pull (as Push gives this advice when trying to Push).

Also here not very handy behavior when I am trying to learn the workflow;-)

**Comment by vreijs** [comment]
By the way are the resulting data-frame (lists) by val or reference? If I use these results in my ARCHAEOCOSMO it seems that the copy to a variable becomes NULL or 0:
This is the code:
    Loc <-as.integer(0)
    print("output swe_calc (i): ")
      print (i) #is result of swe_azalt
      print(paste("value of i$xx[2]: ",i$xx[2]))
      Loc <- i$xX[2]
      print(paste("Loc <- i$xx[2]: ",Loc))


[1] "output swe_calc (i): " 
$`return` [1] 34820  
$xx [1] 293.2899122 -22.1022286   0.9923157   0.0000000   0.0000000   0.0000000  
$serr [1] "SwissEph file 'seplm18.se1' not found in PATH 'C:\\ARCHAEOCOSMO\\ephe\\' \nusing Moshier eph.; "  
[1] "value of i$xx[2]:  -22.102228564914" 
[1] "Loc <- i$xx[2]:  " integer(0)

So why is Loc 0?

So this is one of the mysteries;-) Thanks for your patience...

**Comment by vreijs** [comment]
The issue with a Loc value of 0 or NULL was due to a typo on my side (I did not see that one x in the name was a capital!)!! So my frustration just just due to a typo.

I think I also have a kind f workflow to get swephR installed before starting ARCHAEOCOSMO (using RStudio icons):
library(devtools) (in R)
library(roxygen2) (in R)
Load All # this one does not load devtools or roxygen2) (in RStudio)
rorzygenise() (in R)
document() (in R)
Install and Restart (in RStudio)

Does the above sound logical? Or is there a better workflow?

.

**Comment by rstub** [comment]
Good that you found the solution for Loc!

Concerning your workflow: I would expect that roxygenize() is not necessary when you do document() anyway. In sddition, I think it is possible to tell RStudio to do these steps automatically. I have to cross-check that, though, since I am not using RStudio on this computer.

**Comment by vreijs** [comment]
I found a 'moment' that roxygenise() was important to indeed get all the
names known (document() did not work) or that expert_interface.R needed
this roxygenise()...
I was so naive that I though (hoped) that RStudio would do the correct
workflow. Will also see if it can be automated. But sometimes I have the
idea that there is a kind of two pass process needed: as I have seen that
doing roxyginese() twice, directly after each other, gives a different
behavior of R. I now try to keep my sequence better remembered, so I can
find the best workflow...


P.S. if I do ?expert-interface or ?sweph3-package I see the file:
Arithmetic Operators

**Comment by rstub** [comment]
Does `? expert-interface` or `?swephR-package` work for you? If yes, I think we can close this issue.

**Comment by vreijs** [comment]
Had forgotten that query of mine indeed. I still get the Arithmetic
Operators help file:
"
Arithmetic OperatorsDescription

These unary and binary operators perform arithmetic on numeric or complex
vectors (or objects which can be coerced to them).
Usage

+ x
- x
x + y
x - y
x * y
x / y
x ^ y
x %% y
x %/% y"

**Comment by vreijs** [comment]
I still get this Arithmetic OperatorsDescription help file when doing:  ?swephR-package

**Comment by vreijs** [comment]
Strange I get this, even though I see swephR-package.Rd in the man directory (like the other Rd files, which are correctly displayed). ?swephR and ?swephRdata works though, but adding '-package' it does not...

**Comment by rstub** [comment]
Does it work if you use quotes:

```
?`swephR-package`
```

**Comment by vreijs** [comment]
That works indeed with quotes... Why? Is a '-' interpreted differently?
