### ISSUE TITLE
error message when doing and 'Install and Rebuilt' (in RStudio)

### ISSUE THREAD

**Issue by vreijs** [rstub/swephR#9]
I get this error sometimes directly after pressing 'Install and Rebuilt' in RStudio::
"Error in library.dynam.unload(name, system.file(package = name)) : 
  DLL ‘swephR.dll’ was not loaded

Restarting R session..."

Don't think it is serious, but just wondering.

**Comment by rstub** [comment]
I cannot reproduce this. My guess is that it is specific to RStudio trying to unload a DLL. That is not well supported, which is why most R users simply restart their R session in such cases.
